type = "experience"
title = "Experience"

[[internships]]
primary = "**Tencent Research Institute**"
location = "Beijing, China"
secondary = "Research Intern"
period = "Aug 2025–Oct 2025"

[[internships]]
primary = "**ByteDance**"
location = "Shanghai, China"
secondary = "Business Analytics Intern"
period = "Jun 2025–Jul 2025"

[[internships]]
primary = "**Ant Group Research Institute**"
location = "Shanghai, China"
secondary = "Data & Modeling Intern"
period = "Apr 2024–Jun 2024"

[[awards]]
title = "Outstanding Graduate"
institution = "Shanghai Jiao Tong University"
period = "2026"

[[awards]]
title = "Merit Student"
institution = "Shanghai Jiao Tong University"
period = "2025"

[[awards]]
title = "Academic Scholarship"
institution = "Shanghai Jiao Tong University"
period = "2021–2025"

[[awards]]
title = "Bachelor's Degree with Honors"
institution = "Huazhong University of Science and Technology"
period = "2021"

[[awards]]
title = "National Scholarship"
institution = "Huazhong University of Science and Technology"
period = "2020"

[[awards]]
title = "Outstanding Undergraduate Student"
institution = "Huazhong University of Science and Technology"
period = "2019"
