[[news]]
date = "2026-06"
content = "Presented *Optimal Return Policies with Heterogeneous Search Rewards* at CSAMSE 2026."

[[news]]
date = "2026-06"
content = "I received my Ph.D. in Management Science and Engineering from Shanghai Jiao Tong University."

[[news]]
date = "2026-03"
content = "Our paper, *Why Full Refunds Prevail: A Product Fit Perspective*, was published online in *Production and Operations Management*."

[[news]]
date = "2025-07"
content = "Presented *Managing Product Fit Uncertainty in Online Shopping: On Information Search and Return Shipping Insurance* at CSAMSE 2025."